//
//  IPhoneX5VC.swift
//
//  Created on Jul 20, 2018.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class IPhoneX5VC: NSObject {
    
    
    //MARK: - Canvas Drawings
    
    /// Page 1
    
    class func drawIPhoneX5VC(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 375, height: 812), resizing: ResizingBehavior = .aspectFit) {
        /// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        /// Resize to Target Frame
        context.saveGState()
        let resizedFrame = resizing.apply(rect: CGRect(x: 0, y: 0, width: 375, height: 812), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 375, y: resizedFrame.height / 812)
        
        /// Rectangle 4
        let rectangle4 = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 376, height: 812))
        context.saveGState()
        context.saveGState()
        // Warning: Image fill is not supported.
        context.restoreGState()
        context.saveGState()
        rectangle4.lineWidth = 2
        context.beginPath()
        context.addPath(rectangle4.cgPath)
        context.clip(using: .evenOdd)
        UIColor(white: 0.592, alpha: 1).setStroke()
        rectangle4.stroke()
        context.restoreGState()
        context.restoreGState()
        
        /// TabBar
        // Warning: New symbols are not supported.
        
        /// Лидеры
        let layer = NSMutableAttributedString(string: "Лидеры\n")
        layer.addAttribute(.font, value: UIFont(name: "LucidaGrande", size: 20)!, range: NSRange(location: 0, length: layer.length))
        layer.addAttribute(.kern, value: 0.32, range: NSRange(location: 0, length: layer.length))
        do {
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.alignment = .center
            layer.addAttribute(.paragraphStyle, value: paragraphStyle, range: NSRange(location: 0, length: layer.length))
        }
        layer.addAttribute(.foregroundColor, value: UIColor(white: 0.995, alpha: 1), range: NSRange(location: 0, length: layer.length))
        context.saveGState()
        layer.draw(at: CGPoint(x: 148, y: 45))
        context.restoreGState()
        
        /// leaderboardRect
        // Warning: New symbols are not supported.
        
        /// leaderboardRect
        // Warning: New symbols are not supported.
        
        /// leaderboardRect
        // Warning: New symbols are not supported.
        
        /// leaderboardRect
        // Warning: New symbols are not supported.
        
        /// leaderboardRect
        // Warning: New symbols are not supported.
        
        /// leaderboardRect
        // Warning: New symbols are not supported.
        
        /// Pattern
        // Warning: New symbols are not supported.
        
        /// iPhone X Frame
        // Warning: New symbols are not supported.
        
        /// Rectangle 5
        let rectangle5 = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 77, height: 52))
        context.saveGState()
        context.setAlpha(0)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 26, y: 729)
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        /// Rectangle
        let rectangle = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 103, height: 66))
        context.saveGState()
        context.setAlpha(0.06)
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        do {
            context.translateBy(x: 262, y: 730)
        }
        context.endTransparencyLayer()
        context.restoreGState()
        
        
        context.restoreGState()
    }
    
    
    //MARK: - Canvas Images
    
    /// Page 1
    
    class func imageOfIPhoneX5VC() -> UIImage {
        struct LocalCache {
            static var image: UIImage!
        }
        if LocalCache.image != nil {
            return LocalCache.image
        }
        var image: UIImage
        
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 375, height: 812), false, 0)
        IPhoneX5VC.drawIPhoneX5VC()
        image = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        LocalCache.image = image
        return image
    }
    
    
    //MARK: - Resizing Behavior
    
    enum ResizingBehavior {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.
        
        func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }
            
            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)
            
            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }
            
            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
    
    
}
